apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: discovery-controller
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-controller
  namespace: system
  labels:
    app: discovery-controller
spec:
  selector:
    matchLabels:
      app: discovery-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery-controller
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: discovery-controller-pull-secret
