# Copyright Contributors to the Open Cluster Management project

# permissions for end users to view discoveredclusterrefreshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discoveredclusterrefresh-viewer-role
rules:
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveredclusterrefreshes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveredclusterrefreshes/status
  verbs:
  - get
