# Copyright Contributors to the Open Cluster Management project

# permissions for end users to view discoveredclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discoveredcluster-viewer-role
rules:
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveredclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveredclusters/status
  verbs:
  - get
