# Copyright Contributors to the Open Cluster Management project

# permissions for end users to view discoveryconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discoveryconfig-viewer-role
rules:
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveryconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.open-cluster-management.io
  resources:
  - discoveryconfigs/status
  verbs:
  - get
