apiVersion: v1
data:
  metadata: metadata
kind: Secret
metadata:
  labels:
    cluster.open-cluster-management.io/cloudconnection: ""
    cluster.open-cluster-management.io/provider: crh
  name: ocm-api-token
  namespace: open-cluster-management
type: Opaque
